name: astih
channels:
  - defaults
dependencies:
  - pip:
      - dandi
      - mlcroissant
      - torch<2.4.0
      - axondeepseg==5.0.4
      - monai
      - opencv-python==4.8.1.78
      - stardist
